TakeATrip/TakeATrip.Web/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using TakeATrip.Entities.IdentityDB;
using TakeATrip.Services.Core;

namespace TakeATrip.Web.Controllers
{
    [Authorize]
    public class OrderController : Controller
    {
        private readonly ICartService _cartService;
        private readonly UserManager<ApplicationUser> _userManager;
        public OrderController(
            UserManager<ApplicationUser> userManager, 
            ICartService cartService)
        {
            _cartService = cartService;
            _userManager = userManager;
        }

        public IActionResult YourCart()
        {
            return View();
        }

        public int GetTotalItem()
        {
            string userId = _userManager.GetUserId(User);
            return _cartService.GetTotalItem(userId);
        }
    }
}

TakeATrip/TakeATrip.Web/Controllers/TourController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using TakeATrip.Services.Core;
using TakeATrip.Services.Models.TourModels;
using TakeATrip.Web.ViewModels.TourViewModels;
using System.Security.Claims;
using Microsoft.AspNetCore.Identity;
using TakeATrip.Entities.IdentityDB;

namespace TakeATrip.Web.Controllers
{
    public class TourController : Controller
    {
        private ITourService _tourService;
        private IReviewService _reviewService;
        private IConfiguration _configuration;
        private IMapper _mapper;
        private readonly UserManager<ApplicationUser> _userManager;

        public TourController(ITourService tourService,
                              IReviewService reviewService,
                              IConfiguration configuration,
                              IMapper mapper,
                              UserManager<ApplicationUser> userManager)
        {
            _tourService = tourService;
            _reviewService = reviewService;
            _configuration = configuration;
            _mapper = mapper;
            _userManager = userManager;
        }

        public IActionResult Index()
        {
            var tourPageModel = new TourPage
            {
                TourTypeItem = _tourService.GetTourType()
            };

            return View(tourPageModel);
        }

        public PartialViewResult GetTourList(int pageIndex, int pageSize, string searchText, string location, string tourType)
        {
            var query = new GetTourPageQuery
            {
                PageIndex = pageIndex,
                PageSize = pageSize,
                SearchText = searchText,
                Location = location,
                TourType = tourType,
            };

            var tourPage = _tourService.GetTourPage(query);
            foreach (var item in tourPage.Items)
            {
                item.ThumbNail = GetPath(item.Id, item.ThumbNail);
            }
            return PartialView("_TourPagePartial", tourPage);
        }

        public PartialViewResult GetTourListByOrderBy(string orderBy)
        {
            if (!string.IsNullOrEmpty(orderBy))
            {
                var tourPage = _tourService.GetTourPageByOrderBy(orderBy);

                foreach (var item in tourPage.Items)
                {
                    item.ThumbNail = GetPath(item.Id, item.ThumbNail);
                }
                return PartialView("_TourPagePartial", tourPage);
            }
            return PartialView("_TourPagePartial");
        }

        public IActionResult Detail(string id)
        {
            var tourdetail = _tourService.GetTourDetail(int.Parse(id));
            var tourDetailViewModel = _mapper.Map<TourDetailViewModel>(tourdetail);
            return View(tourDetailViewModel);
        }

        public PartialViewResult GetReview(string id)
        {
            var reviewModel = _reviewService.GetReview(id);
            return PartialView("_ReviewPagePartial", reviewModel);
        }

        public string GetPath(string id, string fileName)
        {

            return _configuration["ImgPath"] + "/" + id + "/" + fileName;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var tourPageModel = new CreateTourViewModel
            {
                TourTypeItem = _tourService.GetTourType()
            };

            return View(tourPageModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateTourViewModel model)
        {
            model.TourTypeItem = _tourService.GetTourType();
            if (ModelState.IsValid)
            {
                var tourModel = _mapper.Map<CreatTourModel>(model);
                var user = await _userManager.GetUserAsync(User);
                tourModel.CreatedBy = user.UserName;
                var result = _tourService.CreateTour(tourModel);
                switch (await result)
                {
                    case 1:
                        return Redirect("/Tour/Index");
                    case -1:
                        ModelState.AddModelError("ModelError", "Cannot save your thumbnail. Please contact to admin");
                        return View(model);
                    case -2:
                        ModelState.AddModelError("ModelError", "Creat tour failed. Please recheck your image");
                        return View(model);
                    default:
                        return Redirect("/Tour/Index");
                }

            }
            ModelState.AddModelError("ModelError", "Please recheck your data");
            return View(model);
        }

        [Authorize]
        public IActionResult TourManagement()
        {
            var tourPageModel = new TourPage
            {
                TourTypeItem = _tourService.GetTourType()
            };

            return View(tourPageModel);
        }

        [Authorize]
        public async Task<PartialViewResult> GetTourManagementList(int pageIndex, int pageSize, string searchText, string location, string tourType)
        {

            var user = await _userManager.GetUserAsync(User);
            var query = new GetTourPageQuery
            {
                PageIndex = pageIndex,
                PageSize = pageSize,
                SearchText = searchText,
                Location = location,
                TourType = tourType,
                CreatedBy = user.UserName
            };

            var tourPage = _tourService.GetTourPage(query);
            foreach (var item in tourPage.Items)
            {
                item.ThumbNail = GetPath(item.Id, item.ThumbNail);
            }
            return PartialView("_TourManagementPartial", tourPage);
        }

        [Authorize]
        [HttpGet]
        public IActionResult Update(string id)
        {
            var tourdetail = _tourService.GetTourDetail(int.Parse(id));

            var updateTourViewModel = _mapper.Map<UpdateTourViewModel>(tourdetail);
            updateTourViewModel.TourTypeItem = _tourService.GetTourType();
            updateTourViewModel.ThumbNailLink = GetPath(updateTourViewModel.Id, updateTourViewModel.ThumbNailLink);
            return View(updateTourViewModel);
        }

        [Authorize]
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(UpdateTourViewModel model)
        {
            model.TourTypeItem = _tourService.GetTourType();
            if (ModelState.IsValid)
            {
                var updateTourModel = _mapper.Map<UpdateTourModel>(model);
                var user = await _userManager.GetUserAsync(User);
                updateTourModel.UpdatedBy = user.UserName;
                var result = _tourService.UpdateTour(updateTourModel);

                switch (await result)
                {
                    case 1:
                        return Redirect("/Tour/TourManagement");
                    case -1:
                        ModelState.AddModelError("ModelError", "Cannot save your thumbnail. Please contact to admin");
                        return View(model);
                    case -2:
                        ModelState.AddModelError("ModelError", "Create tour failed. Please recheck your image");
                        return View(model);
                    default:
                        return Redirect("/Tour/Index");
                }

            }

            ModelState.AddModelError("ModelError", "Please recheck your data");
            return View(model);
        }
    }
}

TakeATrip/TakeATrip.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - TakeATrip</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="~/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="~/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="~/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="~/img/apple-touch-icon-144x144-precomposed.png">

    <!-- BASE CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/vendors.css" rel="stylesheet">
    <link href="~/css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

    <!-- SPECIFIC CSS -->
    <link href="~/css/daterangepicker.css" rel="stylesheet">

    <!-- ALTERNATIVE COLORS CSS -->
    <link href="~/css/color-green.css" id="colors" rel="stylesheet">

    <!-- YOUR CUSTOM CSS -->
    <link href="~/css/custom.css" rel="stylesheet">

    @{
        var isAuthenticated = User.Identity.IsAuthenticated;
    }

</head>
<body>
    <div id="page">
        <header class="header menu_fixed">
            <div id="preloader"><div data-loader="circle-side"></div></div><!-- /Page Preload -->
            <div id="logo">
                <a asp-action="Index" asp-controller="Home">
                    <img src="~/img/logo.png" width="150" height="36" data-retina="true" alt="" class="logo_normal">
                    <img src="~/img/logo_sticky.png" width="150" height="36" data-retina="true" alt="" class="logo_sticky">
                </a>
            </div>
            <ul id="top_menu">
                @if (User.Identity.IsAuthenticated)
                {
                    <li><a asp-controller="Order" asp-action="YourCart" class="cart-menu-btn" title="Cart"><strong id="totalCartItem">0</strong></a></li>
                    <li><a href="wishlist.html" class="wishlist_bt_top" title="Your wishlist">Your wishlist</a></li>
                }
                else
                {
                    <li><a asp-controller="Account" asp-action="Login" class="login" title="Sign In">Sign In</a></li>
                }
            </ul>
            <!-- /top_menu -->
            <a href="#menu" class="btn_mobile">
                <div class="hamburger hamburger--spin" id="hamburger">
                    <div class="hamburger-box">
                        <div class="hamburger-inner"></div>
                    </div>
                </div>
            </a>
            <nav id="menu" class="main-menu">
                <ul>
                    <li>
                        <span><a asp-controller="Tour" asp-action="Index">Tours</a></span>
                    </li>
                    <li>
                        <span><a asp-controller="Hotel" asp-action="Index">Hotels</a></span>
                    </li>
                    @if (User.Identity.IsAuthenticated)
                        {
                            <li>
                                <div><form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm"></form></div>
                                <span><a asp-controller="Manage" asp-action="Profile">@User.Identity.Name</a></span>
                                <ul>
                                    <li><a asp-controller="Manage" asp-action="Profile">Profile</a></li>
                                    <li><a href="index-2.html">Inbox</a></li>
                                    <li><a href="javascript:document.getElementById('logoutForm').submit();">Logout</a></li>
                                </ul>
                            </li>


                        }
                </ul>
            </nav>
        </header>
    </div>
    <main>
        @RenderBody()
    </main>

    <footer>
        <div class="container margin_60_35">
            <div class="row">
                <div class="col-lg-5 col-md-12 p-r-5">
                    <p><img src="~/img/logo.png" width="150" height="36" data-retina="true" alt=""></p>
                    <p>
                        TakeATrip is not a booking agent or tour operator, and does not charge any service fees to users of our site.
                        Our partners (airlines, travel providers, and booking agents) who list airfare, tours, and travel packages on
                        TakeATrip are required to include all fees and surcharges in their listed prices.
                    </p>
                    <div class="follow_us">
                        <ul>
                            <li>Follow us</li>
                            <li><a href="#0"><i class="ti-facebook"></i></a></li>
                            <li><a href="#0"><i class="ti-twitter-alt"></i></a></li>
                            <li><a href="#0"><i class="ti-google"></i></a></li>
                            <li><a href="#0"><i class="ti-pinterest"></i></a></li>
                            <li><a href="#0"><i class="ti-instagram"></i></a></li>
                        </ul>
                    </div>
                </div>
                <div class="col-lg-3 col-md-6 ml-lg-auto">
                    <h5>Useful links</h5>
                    <ul class="links">
                        <li><a asp-controller="Home" asp-action="About">About</a></li>
                        <li><a asp-controller="Account" asp-action="Login">Login</a></li>
                        <li><a asp-controller="Account" asp-action="Register">Register</a></li>
                        <li><a asp-controller="Home" asp-action="Contact">Contacts</a></li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-6">
                    <h5>Contact with Us</h5>
                    <ul class="contacts">
                        <li><a href="tel://61280932400"><i class="ti-mobile"></i> + 61 23 8093 3400</a></li>
                        <li><a href="mailto:info@takeatrip.com"><i class="ti-email"></i> info@takeatrip.com</a></li>
                    </ul>
                </div>
            </div>
            <!--/row-->
            <hr>
            <div class="row">
                <div class="col-lg-6">
                    <ul id="footer-selector">
                        <li>
                            <div class="styled-select" id="lang-selector">
                                <select>
                                    <option value="English" selected>English</option>
                                    <option value="French">French</option>
                                    <option value="Spanish">Spanish</option>
                                    <option value="Russian">Russian</option>
                                </select>
                            </div>
                        </li>
                        <li>
                            <div class="styled-select" id="currency-selector">
                                <select>
                                    <option value="US Dollars" selected>US Dollars</option>
                                    <option value="Euro">Euro</option>
                                </select>
                            </div>
                        </li>
                        <li><img src="~/img/cards_all.svg" alt=""></li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul id="additional_links">
                        <li><a href="#0">Terms and conditions</a></li>
                        <li><a href="#0">Privacy</a></li>
                        <li><span>© 2018 TakeATrip</span></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>

    <div id="toTop"></div><!-- Back to top button -->
    <!-- COMMON SCRIPTS -->
    <script src="~/js/jquery-2.2.4.min.js"></script>
    <script src="~/js/common_scripts.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/assets/validate.js"></script>

    @if (User.Identity.IsAuthenticated)
    {
        <script>
            $.get("/Order/GetTotalItem", function (data, status) {
                $('#totalCartItem').text(data);
            });
        </script>
    }

    @RenderSection("Scripts", required: false)
</body>
</html>

TakeATrip/TakeATrip.Web/Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="Panagea - Premium site template for travel agencies, hotels and restaurant listing.">
    <meta name="author" content="Ansonika">
    <title>@ViewData["Title"] - TakeATrip</title>
    <!-- Favicons-->
    <link rel="shortcut icon" href="~/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="~/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="~/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="~/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="~/img/apple-touch-icon-144x144-precomposed.png">
    <!-- BASE CSS -->
    <link href="~/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/css/style.css" rel="stylesheet">
    <link href="~/css/vendors.css" rel="stylesheet">
    <link href="~/css/icon_fonts/css/all_icons.min.css" rel="stylesheet">

    <!-- ALTERNATIVE COLORS CSS -->
    <link href="~/css/color-green.css" id="colors" rel="stylesheet">
    <!-- YOUR CUSTOM CSS -->
    <link href="~/css/custom.css" rel="stylesheet">

</head>
<body>
    <div id="login_bg">

        <nav id="menu" class="fake_menu"></nav>

        <div id="preloader">
            <div data-loader="circle-side"></div>
        </div>
        <!-- End Preload -->

        <div id="login">
            <aside>
                <figure>
                    <a asp-controller="Home" asp-action="Index"><img src="~/img/logo_sticky.png" width="155" height="36" data-retina="true" alt="" class="logo_sticky"></a>
                </figure>

                @RenderBody()

                <div class="copy">© 2018 TakeATrip</div>
            </aside>
        </div>
    </div>

    <!-- COMMON SCRIPTS -->
    <script src="~/js/jquery-2.2.4.min.js"></script>
    <script src="~/js/common_scripts.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/assets/validate.js"></script>    

    @RenderSection("Scripts", required: false)
</body>
</html>

TakeATrip/TakeATrip.Web/Views/Shared/_PageNavigationPartial.cshtml
@model dynamic

@{
    var maximumVisibleButtons = 7;
    var maxPageNumberButtons = maximumVisibleButtons - 2;
    var midPoint = maxPageNumberButtons / 2;
    var pageNumber = Model.PageIndex + 1;
    var pageSize = Model.PageSize;
    var totalCount = Model.TotalCount;
    int totalPageCount = pageSize != 0 ? (totalCount / pageSize) + (totalCount % pageSize == 0 ? 0 : 1) : 1;
    var startPageIndex = pageNumber > midPoint ? pageNumber - midPoint : 1;
    var endPageIndex = pageNumber + midPoint;
}

<div class="row">
    <div class="col-md-12">
        <ul class="pagination pagination-sm pull-right" data-number-page="@totalPageCount">
            <li><a href="#" class="first-page" aria-label="Fist">First</a></li>
            <li><a href="#" class="previous-page" aria-label="Previous">Previous</a></li>
            @if (startPageIndex > 1)
            {
                <li><a href="#" class="page-index" data-index="@(startPageIndex -2)">...</a></li>
            }

            @for (int i = startPageIndex; i <= endPageIndex; i++)
            {
                if (i <= totalPageCount)
                {
                    var className = i == pageNumber ? "active" : string.Empty;
                    <li class="@className"><a href="#" class="page-index" data-index="@(i - 1)">@i</a></li>
                }
            }

            @if (endPageIndex < totalPageCount)
            {
                <li><a href="#" class="page-index" data-index="@endPageIndex">...</a></li>
            }
            <li><a href="#" class="next-page" aria-label="Next">Next</a></li>
            <li><a href="#" class="last-page" aria-label="Last">Last</a></li>
        </ul>
    </div>
</div>

<style>
    .pagination {
        display: inline-block;
    }

        .pagination a {
            color: black;
            float: left;
            padding: 8px 16px;
            text-decoration: none;
            border: 1px solid #ddd; /* Gray */
        }
    ul li {
        display: inline;
    }

</style>